/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Comparators;

@SuppressWarnings("java:S106")
public class HelloOtus {
    public static void main(String... args) {
        double double1 = Math.random();
        double double2 = Math.random();
        System.out.println("first double = " + double1);
        System.out.println("second double = " + double2);
        System.out.println("maximum of 2 = " + Comparators.max(double1, double2));
    }
}
